apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hostname-app
  name: hostname-app
spec:
  containers:
  - image: docker-repo/hostname:v1
    name: hostname-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
